name: Node CI

on:
  push:
    branches:
      - master

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
      
    - name: npm install, build
      run: make install

    - name: Run Linter
      run: make lint