name: lint

on:
  push:
    branches:
      - master

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: npm install, build
        run: make install

      - name: Run Linter
        run: make lint